<a href="https://colab.research.google.com/github/subash9025/Machine-Learning-Labs/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf


In [ ]:
a = tf.constant([4,7,8])
b = tf.constant([2,8,9])
c = tf.multiply(a,b)
print(c)

tf.Tensor([ 8 56 72], shape=(3,), dtype=int32)


In [ ]:
def fib(n):
		if n== 0 or n== 1:
			return n
		return fib (n- 1) + fib (n- 2) 
fib(6)

8

In [ ]:
nterms = int(input("How many terms? "))


n1, n2 = 0, 1
count = 0


if nterms <= 0:
   print("Please enter a positive integer")

elif nterms == 1:
   print("Fibonacci sequence upto",nterms,":")
   print(n1)

else:
   print("Fibonacci sequence:")
   while count < nterms:
       print(n1)
       nth = n1 + n2
       n1 = n2
       n2 = nth
       count += 1


How many terms? 23
Fibonacci sequence:
0
1
1
2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946
17711


In [18]:
import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
graph = tf.Graph()
with graph.as_default():
  a = tf.placeholder(tf.float64, shape=(3, 3), name='tensor1')
  b = a ** 2
array1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
with tf.Session(graph=graph) as session:
  operation_res = session.run(b, feed_dict={a: array1})
  print("after executing the operation: ")
  print(operation_res)


import tensorflow.compat.v1 as tf
tf.compat.v1.disable_eager_execution()
u = tf.Variable(tf.cast(1,"int64"))
v = tf.Variable(tf.cast(0,"int64"))

update_u = tf.assign(u, tf.math.add(u,v))
update_v = tf.assign(v, tf.math.subtract(u,v))

init = tf.initialize_all_variables()

with tf.Session() as sess:
  sess.run(init)
  for i in range(100):
    print (i, sess.run(v))
    sess.run(update_u)
    sess.run(update_v)


Instructions for updating:
Use `tf.global_variables_initializer` instead.


after executing the operation: 
[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]]
0 0
1 1
2 1
3 2
4 3
5 5
6 8
7 13
8 21
9 34
10 55
11 89
12 144
13 233
14 377
15 610
16 987
17 1597
18 2584
19 4181
20 6765
21 10946
22 17711
23 28657
24 46368
25 75025
26 121393
27 196418
28 317811
29 514229
30 832040
31 1346269
32 2178309
33 3524578
34 5702887
35 9227465
36 14930352
37 24157817
38 39088169
39 63245986
40 102334155
41 165580141
42 267914296
43 433494437
44 701408733
45 1134903170
46 1836311903
47 2971215073
48 4807526976
49 7778742049
50 12586269025
51 20365011074
52 32951280099
53 53316291173
54 86267571272
55 139583862445
56 225851433717
57 365435296162
58 591286729879
59 956722026041
60 1548008755920
61 2504730781961
62 4052739537881
63 6557470319842
64 10610209857723
65 17167680177565
66 27777890035288
67 44945570212853
68 72723460248141
69 117669030460994
70 190392490709135
71 308061521170129
72 498454011879264
73 806515533049393
74 1304969544928657
75 2111485077978050
76 3416454622906707